- name: condition whethe num is less than 10
  hosts: local
  connection: local
  Vars:
    number: 14
  vars_prompt:
    name: number
    prompt: "enter the number"
 
  tasks:
    - name: to check the number if less than 10
      ansible.builtin.debug:
      msg: "entered number is less than 10"
      when: number < 10
    
    - name: to check num if greater than 10
      ansible.builtin.debug:
       msg: "entered number is greater than 10"
       when: number >= 10