- name: loops
  become: yes
  tasks:
    - name: install s/w with loops
      ansible.builtin.package:
        name: "{{item}}""
        state: present
      loop:
      - postfix
      - ansible
      - nginx
  hosts: web1