- name: loops demo
  hosts: web
  become: yes
  tasks:
   - name: filteration 
     ansible.builtin.package:
      name: {{item.name}}
      state: {{item.state}}
     loop:
     - { name: 'nginx' ,state: 'absent'}
     - { name: 'ansible' , state: present}