- name: print the msg
  hosts: web
  vars:
    course: "Devops"
    duration: "120Hrs"
  tasks:
    - name: print the msg
      ansible.builtin.debug:
       msg: "Hi I'm Learning {{course}} of {{duration}} time"