- name: variables to be printed
  hosts: web1
  vars: #play-level 
    course: Devops
    duration: 120Hrs
  tasks:
    - name: print the info 
      ansible.builtin.debug:
       msg: "Hi,! I'm learning {{course of {{duration}}"

    - name: print the task2 info
      vars:
        course: Ansible
      ansible.builtin.debug:
       msg: "I'm learning {{course}} of duration {{duration}}"